steps:

- name: 'python:3.9'
  entrypoint: 'pip'
  args: ['install', '-r', 'requirements.txt', '--user']
  id: 'Install Dependencies'
  waitFor: ['Clone Repository']

options:
  logging: CLOUD_LOGGING_ONLY