steps:
  # Krok 1: Instalacja zależności Pythona.
- name: 'python:3.9'
  entrypoint: 'pip'
  args: ['install', '-r', 'requirements.txt', '--user']
  id: 'Install Dependencies'

  # Krok 3: Budowanie obrazu Docker dla komponentów.
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - '$_CUSTOM_COMPONENT_IMAGE_URI'
    - '$_COMPONENTS_DIR_PATH'
  id: 'Build Custom Component Image'

 # Krok 4: Kompilacja potoku do formatu JSON.
- name: 'python:3.9'
  entrypoint: 'python3'
  args: ['$_PIPELINE_SCRIPT_PATH']
  id: 'Compile Pipeline'
  env:
    - 'CUSTOM_COMPONENT_IMAGE_URI=$_CUSTOM_COMPONENT_IMAGE_URI'
  waitFor: ['Build Custom Component Image']

  # Krok 5: Przesłanie skompilowanej definicji potoku do GCS.
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'pipeline.json', '$_PIPELINE_GCS_PATH/$_PIPELINE_NAME.json']
  id: 'Upload Pipeline to GCS'
  waitFor: ['Compile Pipeline']
images:
  - '$_CUSTOM_COMPONENT_IMAGE_URI'
options:
  logging: CLOUD_LOGGING_ONLY