# Ten plik jest uruchamiany przez trigger nasłuchujący na wiadomości Pub/Sub.
# Jego zadaniem jest uruchomienie gotowego, skompilowanego potoku wdrożeniowego.
steps:
- name: 'gcr.io/google-cloud-builders/gcloud'
  id: 'Trigger Deployment Pipeline'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      # Wiadomość z Pub/Sub jest dostępna w zmiennej $$BODY, zakodowana w base64.
      # Dekodujemy ją i wyciągamy ID modelu za pomocą narzędzia `jq`.
      # Najpierw instalujemy jq.
      apt-get update && apt-get install -y jq

      MODEL_ID=$(echo $$BODY | base64 -d | jq -r .model_resource_name)
      
      # Sprawdzamy, czy udało się odczytać ID modelu.
      if [ -z "$$MODEL_ID" ] || [ "$$MODEL_ID" == "null" ]; then
        echo "Błąd: Nie udało się odczytać ID modelu z wiadomości Pub/Sub."
        exit 1
      fi

      echo "Uruchamianie wdrożenia dla modelu: $$MODEL_ID"

      # Uruchamiamy gotowy potok z GCS, przekazując wszystkie wymagane parametry.
      gcloud ai pipelines run \
        --pipeline=gs://vertex-ai-bucket-s25537/pipelines/deployment_pipeline.json \
        --region=$_REGION \
        --project=$PROJECT_ID \
        --display-name="run-deployment-pubsub-$BUILD_ID" \
        --service-account=$_SERVICE_ACCOUNT \
        --parameter=model_resource_name="$$MODEL_ID" \
        --parameter=project_id="$PROJECT_ID" \
        --parameter=region="$_REGION" \
        --parameter=endpoint_name="$_ENDPOINT_NAME"
  logging: CLOUD_LOGGING_ONLY