# Ten plik jest uruchamiany przez trigger nasłuchujący na wiadomości Pub/Sub.
# Jego zadaniem jest uruchomienie gotowego, skompilowanego potoku wdrożeniowego.
steps:
- name:  'gcr.io/cloud-builders/gcloud'
  id: 'Trigger Deployment Pipeline'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      # Sprawdzamy, czy udało się odczytać ID modelu.
      if [ -z "$_MODEL_RESOURCE_NAME" ]; then
        echo "Błąd: Zmienna _MODEL_RESOURCE_NAME jest pusta."
        echo "Upewnij się, że w triggerze Cloud Build zdefiniowano podstawienie:"
        exit 1
      fi

      echo "Uruchamianie wdrożenia dla modelu:  $_MODEL_RESOURCE_NAME"

      # Uruchamiamy gotowy potok z GCS, przekazując wszystkie wymagane parametry.
      gcloud ai pipelines run \
        --pipeline=gs://vertex-ai-bucket-s25537/pipelines/deployment_pipeline.json \
        --region=$_REGION \
        --project=$PROJECT_ID \
        --display-name="run-deployment-pubsub-$BUILD_ID" \
        --service-account=$_SERVICE_ACCOUNT \
        --parameter=model_resource_name=" $_MODEL_RESOURCE_NAME" \
        --parameter=project_id="$PROJECT_ID" \
        --parameter=region="$_REGION" \
        --parameter=endpoint_name="$_ENDPOINT_NAME"

options:
  logging: CLOUD_LOGGING_ONLY