parameter_values:
  gcs_data_path: "gs://data-s25537/penguins.csv"
  project_id: "mlops-on-gcp-s25537"
  region: "us-central1"
  model_name: "svc-model"
  test_split_ratio: 0.3
  min_accuracy_threshold: 95.0